FROM --platform=amd64 node:24-alpine

RUN apk update && apk upgrade && apk add openssl

WORKDIR /pinpin

COPY --chown=node:node . .

RUN npm ci 

RUN npm run build

USER node

CMD [ "node", "dist/main.js"]