on:
  pull_request:
    branches: [main]

name: Build Docker

jobs:
  docker-build-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: Backend
          push: true
          tags: ghcr.io/clueless-coders/pinpin/pinpin-api:${{ github.ref_name}}
